services:
  pdffullsearch:
    image: pdffullsearch
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000 --nothreading --noreload"]
    ports:
      - 8000:8000
      - 5678:5678

    depends_on:
      elasticsearch:
        condition: service_healthy
      db:
        condition: service_healthy
      ollama:
        condition: service_started
      tika:
        condition: service_started
    networks:
      - elk-network
    restart: always
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    entrypoint:
      [
        "/bin/bash",
        "-c",
        "ollama serve & sleep 5 && ollama pull jina/jina-embeddings-v2-base-es && wait",
      ]
    volumes:
      - ollama-models:/root/.ollama 
    networks:
      - elk-network
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=5s || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elk-network
    restart: always

  tika:
    # Use the official Apache Tika Docker image from Docker Hub
    image: apache/tika:latest
    # Map port 9998 on the host to port 9998 in the container
    ports:
      - "9998:9998"
    # Optional: ensure container restarts if it stops unexpectedly
    networks:
      - elk-network
    restart: always

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - elk-network
    restart: always
      
networks:
  elk-network:
    driver: bridge

volumes:
  postgres_data:
  esdata:
    driver: local
  ollama-models:
    driver: local

