# Generated by Django 6.0.1 on 2026-02-05 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdffullsearch_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='PDFFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('metadata', models.TextField()),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='categories', to='pdffullsearch_backend.category')),
            ],
            options={
                'verbose_name_plural': 'pdf files',
            },
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
